services:
  redis-server:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    container_name: redis-server

  python-celery:
    build: .
    restart: always
    depends_on:
      - redis-server
    environment:
      REDIS_HOST: redis-server
      REDIS_PORT: 6379
    container_name: python-celery